/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.lib.audio.nativeaudio;

public class ADSR {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ADSR(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ADSR obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NativeAudioEngineJNI.delete_ADSR(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ADSR() {
    this(NativeAudioEngineJNI.new_ADSR(), true);
  }

  public ADSR clone() {
    long cPtr = NativeAudioEngineJNI.ADSR_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new ADSR(cPtr, false);
  }

  public void cloneEnvelopes(ADSR source) {
    NativeAudioEngineJNI.ADSR_cloneEnvelopes(swigCPtr, this, ADSR.getCPtr(source), source);
  }

  public void setBufferLength(int bufferLength) {
    NativeAudioEngineJNI.ADSR_setBufferLength(swigCPtr, this, bufferLength);
  }

  public int getBufferLength() {
    return NativeAudioEngineJNI.ADSR_getBufferLength(swigCPtr, this);
  }

  public float getAttack() {
    return NativeAudioEngineJNI.ADSR_getAttack(swigCPtr, this);
  }

  public float getDecay() {
    return NativeAudioEngineJNI.ADSR_getDecay(swigCPtr, this);
  }

  public float getSustain() {
    return NativeAudioEngineJNI.ADSR_getSustain(swigCPtr, this);
  }

  public float getRelease() {
    return NativeAudioEngineJNI.ADSR_getRelease(swigCPtr, this);
  }

  public void setAttack(float aValue) {
    NativeAudioEngineJNI.ADSR_setAttack(swigCPtr, this, aValue);
  }

  public void setDecay(float aValue) {
    NativeAudioEngineJNI.ADSR_setDecay(swigCPtr, this, aValue);
  }

  public void setSustain(float aValue) {
    NativeAudioEngineJNI.ADSR_setSustain(swigCPtr, this, aValue);
  }

  public void setRelease(float aValue) {
    NativeAudioEngineJNI.ADSR_setRelease(swigCPtr, this, aValue);
  }

  public void apply(SWIGTYPE_p_AudioBuffer inputBuffer) {
    NativeAudioEngineJNI.ADSR_apply__SWIG_0(swigCPtr, this, SWIGTYPE_p_AudioBuffer.getCPtr(inputBuffer));
  }

  public void apply(SWIGTYPE_p_AudioBuffer inputBuffer, int eventOffset) {
    NativeAudioEngineJNI.ADSR_apply__SWIG_1(swigCPtr, this, SWIGTYPE_p_AudioBuffer.getCPtr(inputBuffer), eventOffset);
  }

}
