/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.lib.audio.nativeaudio;

public class cachedSample {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected cachedSample(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(cachedSample obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NativeAudioEngineJNI.delete_cachedSample(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSampleLength(int value) {
    NativeAudioEngineJNI.cachedSample_sampleLength_set(swigCPtr, this, value);
  }

  public int getSampleLength() {
    return NativeAudioEngineJNI.cachedSample_sampleLength_get(swigCPtr, this);
  }

  public void setSampleBuffer(SWIGTYPE_p_AudioBuffer value) {
    NativeAudioEngineJNI.cachedSample_sampleBuffer_set(swigCPtr, this, SWIGTYPE_p_AudioBuffer.getCPtr(value));
  }

  public SWIGTYPE_p_AudioBuffer getSampleBuffer() {
    long cPtr = NativeAudioEngineJNI.cachedSample_sampleBuffer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_AudioBuffer(cPtr, false);
  }

  public cachedSample() {
    this(NativeAudioEngineJNI.new_cachedSample(), true);
  }

}
