/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.lib.audio.nativeaudio;

public class LFO {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected LFO(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LFO obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NativeAudioEngineJNI.delete_LFO(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public LFO() {
    this(NativeAudioEngineJNI.new_LFO(), true);
  }

  public float getRate() {
    return NativeAudioEngineJNI.LFO_getRate(swigCPtr, this);
  }

  public void setRate(float value) {
    NativeAudioEngineJNI.LFO_setRate(swigCPtr, this, value);
  }

  public int getWave() {
    return NativeAudioEngineJNI.LFO_getWave(swigCPtr, this);
  }

  public void setWave(int value) {
    NativeAudioEngineJNI.LFO_setWave(swigCPtr, this, value);
  }

  public void generate() {
    NativeAudioEngineJNI.LFO_generate(swigCPtr, this);
  }

  public SWIGTYPE_p_WaveTable getTable() {
    long cPtr = NativeAudioEngineJNI.LFO_getTable(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_WaveTable(cPtr, false);
  }

  public final static double MAX_LFO_RATE = NativeAudioEngineJNI.LFO_MAX_LFO_RATE_get();
  public final static double MIN_LFO_RATE = NativeAudioEngineJNI.LFO_MIN_LFO_RATE_get();
  public final static int WAVE_TABLE_PRECISION = NativeAudioEngineJNI.LFO_WAVE_TABLE_PRECISION_get();
}
