/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.lib.audio.nativeaudio;

public interface NativeAudioEngineConstants {
  public final static double M_PI = NativeAudioEngineJNI.M_PI_get();
  public final static int MAX_FRAME_LENGTH = NativeAudioEngineJNI.MAX_FRAME_LENGTH_get();
}
