/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.lib.audio.nativeaudio;

public class NativeAudioEngine implements NativeAudioEngineConstants {
  public static SWIGTYPE_p_int new_int_array(int nelements) {
    long cPtr = NativeAudioEngineJNI.new_int_array(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public static void delete_int_array(SWIGTYPE_p_int ary) {
    NativeAudioEngineJNI.delete_int_array(SWIGTYPE_p_int.getCPtr(ary));
  }

  public static int int_array_getitem(SWIGTYPE_p_int ary, int index) {
    return NativeAudioEngineJNI.int_array_getitem(SWIGTYPE_p_int.getCPtr(ary), index);
  }

  public static void int_array_setitem(SWIGTYPE_p_int ary, int index, int value) {
    NativeAudioEngineJNI.int_array_setitem(SWIGTYPE_p_int.getCPtr(ary), index, value);
  }

  public static void init() {
    NativeAudioEngineJNI.init();
  }

  public static void start() {
    NativeAudioEngineJNI.start();
  }

  public static void stop() {
    NativeAudioEngineJNI.stop();
  }

  public static void reset() {
    NativeAudioEngineJNI.reset();
  }

  public static ProcessingChain getMasterBusProcessors() {
    long cPtr = NativeAudioEngineJNI.getMasterBusProcessors();
    return (cPtr == 0) ? null : new ProcessingChain(cPtr, false);
  }

  public static void smbFft(SWIGTYPE_p_float fftBuffer, int fftFrameSize, int sign) {
    NativeAudioEngineJNI.smbFft(SWIGTYPE_p_float.getCPtr(fftBuffer), fftFrameSize, sign);
  }

  public static float smbAtan2(float x, float y) {
    return NativeAudioEngineJNI.smbAtan2(x, y);
  }

  public static void set_sampleMap(SWIGTYPE_p_std__mapT_std__string_cachedSample_t value) {
    NativeAudioEngineJNI._sampleMap_set(SWIGTYPE_p_std__mapT_std__string_cachedSample_t.getCPtr(value));
  }

  public static SWIGTYPE_p_std__mapT_std__string_cachedSample_t get_sampleMap() {
    long cPtr = NativeAudioEngineJNI._sampleMap_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__mapT_std__string_cachedSample_t(cPtr, false);
  }

}
