/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.lib.audio.nativeaudio;

public class PercussionTypes {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PercussionTypes(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PercussionTypes obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NativeAudioEngineJNI.delete_PercussionTypes(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PercussionTypes() {
    this(NativeAudioEngineJNI.new_PercussionTypes(), true);
  }

  public final static class Types {
    public final static PercussionTypes.Types KICK_808 = new PercussionTypes.Types("KICK_808", NativeAudioEngineJNI.PercussionTypes_KICK_808_get());
    public final static PercussionTypes.Types STICK = new PercussionTypes.Types("STICK", NativeAudioEngineJNI.PercussionTypes_STICK_get());
    public final static PercussionTypes.Types SNARE = new PercussionTypes.Types("SNARE", NativeAudioEngineJNI.PercussionTypes_SNARE_get());
    public final static PercussionTypes.Types HI_HAT = new PercussionTypes.Types("HI_HAT", NativeAudioEngineJNI.PercussionTypes_HI_HAT_get());

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static Types swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + Types.class + " with value " + swigValue);
    }

    private Types(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private Types(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private Types(String swigName, Types swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static Types[] swigValues = { KICK_808, STICK, SNARE, HI_HAT };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
