/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.lib.audio.nativeaudio;

public class SWIGTYPE_p_std__mapT_std__string_cachedSample_t {
  private long swigCPtr;

  protected SWIGTYPE_p_std__mapT_std__string_cachedSample_t(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_std__mapT_std__string_cachedSample_t() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_std__mapT_std__string_cachedSample_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

