/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.lib.audio.nativeaudio;

public class Arpeggiator {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Arpeggiator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Arpeggiator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NativeAudioEngineJNI.delete_Arpeggiator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Arpeggiator() {
    this(NativeAudioEngineJNI.new_Arpeggiator(), true);
  }

  public int getStepSize() {
    return NativeAudioEngineJNI.Arpeggiator_getStepSize(swigCPtr, this);
  }

  public void setStepSize(int value) {
    NativeAudioEngineJNI.Arpeggiator_setStepSize(swigCPtr, this, value);
  }

  public int getAmountOfSteps() {
    return NativeAudioEngineJNI.Arpeggiator_getAmountOfSteps(swigCPtr, this);
  }

  public void setAmountOfSteps(int value) {
    NativeAudioEngineJNI.Arpeggiator_setAmountOfSteps(swigCPtr, this, value);
  }

  public int getShiftForStep(int step) {
    return NativeAudioEngineJNI.Arpeggiator_getShiftForStep(swigCPtr, this, step);
  }

  public void setShiftForStep(int step, int shift) {
    NativeAudioEngineJNI.Arpeggiator_setShiftForStep(swigCPtr, this, step, shift);
  }

  public int getStep() {
    return NativeAudioEngineJNI.Arpeggiator_getStep(swigCPtr, this);
  }

  public boolean peek() {
    return NativeAudioEngineJNI.Arpeggiator_peek(swigCPtr, this);
  }

  public float getPitchForStep(int step, float basePitch) {
    return NativeAudioEngineJNI.Arpeggiator_getPitchForStep(swigCPtr, this, step, basePitch);
  }

  public void cloneProperties(Arpeggiator source) {
    NativeAudioEngineJNI.Arpeggiator_cloneProperties(swigCPtr, this, Arpeggiator.getCPtr(source), source);
  }

  public Arpeggiator clone() {
    long cPtr = NativeAudioEngineJNI.Arpeggiator_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new Arpeggiator(cPtr, false);
  }

  public final static int MAX_STEPS = NativeAudioEngineJNI.Arpeggiator_MAX_STEPS_get();
}
