/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.lib.audio.nativeaudio;

public class BaseCacheableAudioEvent extends BaseAudioEvent {
  private long swigCPtr;

  protected BaseCacheableAudioEvent(long cPtr, boolean cMemoryOwn) {
    super(NativeAudioEngineJNI.BaseCacheableAudioEvent_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BaseCacheableAudioEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NativeAudioEngineJNI.delete_BaseCacheableAudioEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BaseCacheableAudioEvent() {
    this(NativeAudioEngineJNI.new_BaseCacheableAudioEvent(), true);
  }

  public void setAutoCache(boolean value) {
    NativeAudioEngineJNI.BaseCacheableAudioEvent_setAutoCache(swigCPtr, this, value);
  }

  public void cache(boolean doCallback) {
    NativeAudioEngineJNI.BaseCacheableAudioEvent_cache(swigCPtr, this, doCallback);
  }

  public boolean isCached() {
    return NativeAudioEngineJNI.BaseCacheableAudioEvent_isCached(swigCPtr, this);
  }

  public void setBulkCacheable(boolean value) {
    NativeAudioEngineJNI.BaseCacheableAudioEvent_setBulkCacheable(swigCPtr, this, value);
  }

}
