/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.lib.audio.nativeaudio;

public class BulkCacher {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected BulkCacher(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BulkCacher obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NativeAudioEngineJNI.delete_BulkCacher(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BulkCacher(boolean sequential) {
    this(NativeAudioEngineJNI.new_BulkCacher(sequential), true);
  }

  public void addToQueue(SWIGTYPE_p_std__vectorT_BaseCacheableAudioEvent_p_t aEvents) {
    NativeAudioEngineJNI.BulkCacher_addToQueue__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__vectorT_BaseCacheableAudioEvent_p_t.getCPtr(aEvents));
  }

  public void addToQueue(BaseCacheableAudioEvent aEvent) {
    NativeAudioEngineJNI.BulkCacher_addToQueue__SWIG_1(swigCPtr, this, BaseCacheableAudioEvent.getCPtr(aEvent), aEvent);
  }

  public boolean removeFromQueue(BaseCacheableAudioEvent aEvent) {
    return NativeAudioEngineJNI.BulkCacher_removeFromQueue(swigCPtr, this, BaseCacheableAudioEvent.getCPtr(aEvent), aEvent);
  }

  public boolean hasQueue() {
    return NativeAudioEngineJNI.BulkCacher_hasQueue(swigCPtr, this);
  }

  public void cacheQueue() {
    NativeAudioEngineJNI.BulkCacher_cacheQueue(swigCPtr, this);
  }

  public void clearQueue() {
    NativeAudioEngineJNI.BulkCacher_clearQueue(swigCPtr, this);
  }

}
