/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.lib.audio.nativeaudio;

public class Decimator extends BaseProcessor {
  private long swigCPtr;

  protected Decimator(long cPtr, boolean cMemoryOwn) {
    super(NativeAudioEngineJNI.Decimator_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Decimator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NativeAudioEngineJNI.delete_Decimator(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Decimator(int bits, float rate) {
    this(NativeAudioEngineJNI.new_Decimator(bits, rate), true);
  }

  public int getBits() {
    return NativeAudioEngineJNI.Decimator_getBits(swigCPtr, this);
  }

  public void setBits(int value) {
    NativeAudioEngineJNI.Decimator_setBits(swigCPtr, this, value);
  }

  public float getRate() {
    return NativeAudioEngineJNI.Decimator_getRate(swigCPtr, this);
  }

  public void setRate(float value) {
    NativeAudioEngineJNI.Decimator_setRate(swigCPtr, this, value);
  }

  public void process(SWIGTYPE_p_AudioBuffer sampleBuffer, boolean isMonosource) {
    NativeAudioEngineJNI.Decimator_process(swigCPtr, this, SWIGTYPE_p_AudioBuffer.getCPtr(sampleBuffer), isMonosource);
  }

}
