/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.lib.audio.nativeaudio;

public class DrumTimbres {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DrumTimbres(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DrumTimbres obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NativeAudioEngineJNI.delete_DrumTimbres(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DrumTimbres() {
    this(NativeAudioEngineJNI.new_DrumTimbres(), true);
  }

  public final static class Timbres {
    public final static DrumTimbres.Timbres LIGHT = new DrumTimbres.Timbres("LIGHT");
    public final static DrumTimbres.Timbres GRAVEL = new DrumTimbres.Timbres("GRAVEL");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static Timbres swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + Timbres.class + " with value " + swigValue);
    }

    private Timbres(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private Timbres(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private Timbres(String swigName, Timbres swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static Timbres[] swigValues = { LIGHT, GRAVEL };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
