/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.lib.audio.nativeaudio;

public class Finalizer extends Limiter {
  private long swigCPtr;

  protected Finalizer(long cPtr, boolean cMemoryOwn) {
    super(NativeAudioEngineJNI.Finalizer_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Finalizer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NativeAudioEngineJNI.delete_Finalizer(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Finalizer(float attackMs, float releaseMs, int sampleRate, int amountOfChannels) {
    this(NativeAudioEngineJNI.new_Finalizer(attackMs, releaseMs, sampleRate, amountOfChannels), true);
  }

  public void process(SWIGTYPE_p_AudioBuffer sampleBuffer, boolean isMonoSource) {
    NativeAudioEngineJNI.Finalizer_process(swigCPtr, this, SWIGTYPE_p_AudioBuffer.getCPtr(sampleBuffer), isMonoSource);
  }

}
