/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.lib.audio.nativeaudio;

public class PitchShifter extends BaseProcessor {
  private long swigCPtr;

  protected PitchShifter(long cPtr, boolean cMemoryOwn) {
    super(NativeAudioEngineJNI.PitchShifter_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PitchShifter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NativeAudioEngineJNI.delete_PitchShifter(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PitchShifter(float shiftAmount, int osampAmount) {
    this(NativeAudioEngineJNI.new_PitchShifter(shiftAmount, osampAmount), true);
  }

  public void process(SWIGTYPE_p_AudioBuffer sampleBuffer, boolean isMonoSource) {
    NativeAudioEngineJNI.PitchShifter_process(swigCPtr, this, SWIGTYPE_p_AudioBuffer.getCPtr(sampleBuffer), isMonoSource);
  }

  public boolean isCacheable() {
    return NativeAudioEngineJNI.PitchShifter_isCacheable(swigCPtr, this);
  }

  public void setPitchShift(float value) {
    NativeAudioEngineJNI.PitchShifter_pitchShift_set(swigCPtr, this, value);
  }

  public float getPitchShift() {
    return NativeAudioEngineJNI.PitchShifter_pitchShift_get(swigCPtr, this);
  }

}
