/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package nl.igorski.lib.audio.nativeaudio;

public class SampleEvent extends BaseAudioEvent {
  private long swigCPtr;

  protected SampleEvent(long cPtr, boolean cMemoryOwn) {
    super(NativeAudioEngineJNI.SampleEvent_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SampleEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NativeAudioEngineJNI.delete_SampleEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SampleEvent() {
    this(NativeAudioEngineJNI.new_SampleEvent__SWIG_0(), true);
  }

  public SampleEvent(BaseInstrument aInstrument) {
    this(NativeAudioEngineJNI.new_SampleEvent__SWIG_1(BaseInstrument.getCPtr(aInstrument), aInstrument), true);
  }

  public int getBufferRangeStart() {
    return NativeAudioEngineJNI.SampleEvent_getBufferRangeStart(swigCPtr, this);
  }

  public void setBufferRangeStart(int value) {
    NativeAudioEngineJNI.SampleEvent_setBufferRangeStart(swigCPtr, this, value);
  }

  public int getBufferRangeEnd() {
    return NativeAudioEngineJNI.SampleEvent_getBufferRangeEnd(swigCPtr, this);
  }

  public void setBufferRangeEnd(int value) {
    NativeAudioEngineJNI.SampleEvent_setBufferRangeEnd(swigCPtr, this, value);
  }

  public int getReadPointer() {
    return NativeAudioEngineJNI.SampleEvent_getReadPointer(swigCPtr, this);
  }

  public SWIGTYPE_p_AudioBuffer synthesize(int aBufferLength) {
    long cPtr = NativeAudioEngineJNI.SampleEvent_synthesize(swigCPtr, this, aBufferLength);
    return (cPtr == 0) ? null : new SWIGTYPE_p_AudioBuffer(cPtr, false);
  }

  public void setSample(SWIGTYPE_p_AudioBuffer sampleBuffer) {
    NativeAudioEngineJNI.SampleEvent_setSample(swigCPtr, this, SWIGTYPE_p_AudioBuffer.getCPtr(sampleBuffer));
  }

  public void addToSequencer() {
    NativeAudioEngineJNI.SampleEvent_addToSequencer(swigCPtr, this);
  }

  public void removeFromSequencer() {
    NativeAudioEngineJNI.SampleEvent_removeFromSequencer(swigCPtr, this);
  }

  public void swapInstrument(BaseInstrument aInstrument) {
    NativeAudioEngineJNI.SampleEvent_swapInstrument(swigCPtr, this, BaseInstrument.getCPtr(aInstrument), aInstrument);
  }

  public void mixBuffer(SWIGTYPE_p_AudioBuffer outputBuffer, int bufferPos, int minBufferPosition, int maxBufferPosition, boolean loopStarted, int loopOffset, boolean useChannelRange) {
    NativeAudioEngineJNI.SampleEvent_mixBuffer(swigCPtr, this, SWIGTYPE_p_AudioBuffer.getCPtr(outputBuffer), bufferPos, minBufferPosition, maxBufferPosition, loopStarted, loopOffset, useChannelRange);
  }

  public boolean getBufferForRange(SWIGTYPE_p_AudioBuffer buffer, int readPos) {
    return NativeAudioEngineJNI.SampleEvent_getBufferForRange(swigCPtr, this, SWIGTYPE_p_AudioBuffer.getCPtr(buffer), readPos);
  }

  public void playNow() {
    NativeAudioEngineJNI.SampleEvent_playNow(swigCPtr, this);
  }

}
